### PR TITLE
DEVENGAGE-2683 doc updates

### PR DESCRIPTION
**Pull request by timsmithgenesys**
The changes in this initial PR do the following:

- add a shared script to create an index of the markdown files generated for an SDK's documentation -- was previously done by the dev center's build process
- invoke the doc indexing script for java and javascript builds
- update templates for java and javascript to format for the new doc viewer app and some formatting fixes
- moves node packages into the javascript SDK's package file instead of installing globally and invokes them accordingly -- the compile script wasn't working locally due to some issue resolving a very old version of rollup. Putting them in the dev dependencies of the package and invoking them from the node_modules folder works both locally and on jenkins.

If these changes look good, I'll proceed with the rest of the SDKs and update the PR.

### CODE REVIEW

**Comment by timsmithgenesys** [comment]
PR for the UI app: https://github.com/purecloudlabs/genesys-cloud-platform-client-doc-viewer/pull/1

Java SDK docs: https://mypurecloud.github.io/platform-client-sdk-java/

JavaScript SDK docs: https://mypurecloud.github.io/platform-client-sdk-javascript/

**Review by diemenschmaschine92 — APPROVED** [review]

**Review by HemanthDogiparthi12 — APPROVED** [review]

**Review by dginty4 — APPROVED** [review]

**Comment by timsmithgenesys** [comment]
python docs: https://mypurecloud.github.io/platform-client-sdk-python

**Comment by timsmithgenesys** [comment]
.NET docs https://mypurecloud.github.io/platform-client-sdk-dotnet

**Comment by timsmithgenesys** [comment]
ios docs https://mypurecloud.github.io/platform-client-sdk-ios/

**Comment by timsmithgenesys** [comment]
javascript guest docs https://mypurecloud.github.io/purecloud-guest-chat-client-javascript

**Comment by timsmithgenesys** [comment]
cli docs https://mypurecloud.github.io/platform-client-sdk-cli/

**Comment by timsmithgenesys** [comment]
webmessaging sdk currently can't build due to their openapi v3 update being deployed to production. Once they fix it, the docs would be published here: https://mypurecloud.github.io/web-messaging-sdk-java/.

**Review by carnellj-genesys — APPROVED** [review]

**Pull request merged**
