### PR TITLE
session object is not returning an id anymore

### PR DESCRIPTION
**Pull request by gartcimore**
session object is not returning an id anymore

### CODE REVIEW

**Comment by gartcimore** [comment]
@Jm-47 @ConorCrokeGenesys if you have any comments

**Comment by timsmithgenesys** [comment]
@gartcimore has a breaking change to the contract been announced on the dev forum?

**Comment by gartcimore** [comment]
No, it has not been announced

**Comment by gartcimore** [comment]
Hello @timsmithgenesys, bumping this for review

**Comment by timsmithgenesys** [comment]
@gartcimore I don't own this repo. Please work with the SDK team for review.

**Comment by gartcimore** [comment]
After talking with @michaeljroddy , tagging also @charliecon @dginty4 for review

**Review by michaeljroddy — APPROVED** [review]

**Pull request merged**
